[package]
name = "scoundrel-cards"
description = "Scoundrel (playing card roguelike) in Rust"
license = "MIT"
repository = "https://github.com/Br1ght0ne/scoundrel"
version = "0.1.0"
edition = "2021"

[dependencies]
cardpack = "0.5.4"
color-eyre = "0.6.3"
dialoguer = "0.11.0"
thiserror = "2.0.11"
