name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Install latest nextest release
      uses: taiki-e/install-action@nextest
    - name: Test with latest nextest release
      uses: actions-rs/cargo@v1
      with:
        command: nextest
        args: run
